Algoritmo "terreno"


Var


  largura, comprimento, metroQuadrado, preco, area : real


Inicio

 escreva ("Digite a largura do terreno")
 leia (largura)
 escreva("Digite o comprimento do terreno")
 leia (comprimento)
 escreva("Digite o valor do metroQuadrado")
 leia (metroQuadrado)
 
 area <- largura * comprimento
 preco <- area * metroQuadrado
 
 escreval ("Area do terreno = ", area:8:2)
 escreval ("Preco do terreno = ", preco:8:2)


Fimalgoritmo